### ISSUE TITLE
Deploy to server

### ISSUE THREAD

**Issue by MeNsaaH** [NUKSI911/SUG-POLL-WEBSITE#2]

**Comment by MeNsaaH** [comment]
@NUKSI911 to deploy to the server you must first create the virtualenv then replicate the procedures as shown on README

**Comment by NUKSI911** [comment]
alright will do 
have already created the virtualenv ,and also used gunicorn and nginx server for the static url

**Comment by MeNsaaH** [comment]
You can get back to me on any issue

**Comment by NUKSI911** [comment]
alright man

**Comment by NUKSI911** [comment]
did u guys enter school today

**Comment by MeNsaaH** [comment]
No lab key

**Comment by NUKSI911** [comment]
yea i remember

**Comment by NUKSI911** [comment]
have changed my desktop environment to budgie its kinda beautiful

**Comment by MeNsaaH** [comment]
Toh, good for you. Just try run this deploy make I see. If possible send me the server ssh link and password to my email So I go see wetin you dey do

**Comment by NUKSI911** [comment]
k man

**Comment by NUKSI911** [comment]
this is the url http://178.79.133.99:8800/
havent added http or the custom name

**Comment by NUKSI911** [comment]
http://178.79.133.99 this is it
